# Generated by Django 2.2.6 on 2021-07-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('hotels', '0002_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_category', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена за сутки:'),
            preserve_default=False,
        ),
    ]
