# Generated by Django 2.2.6 on 2021-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20210721_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена за сутки:'),
        ),
    ]
