# Generated by Django 2.2.6 on 2021-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20210721_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.CharField(blank=True, default='Нет', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за сутки:'),
        ),
    ]
