# Generated by Django 2.2.6 on 2021-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20210722_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.CharField(blank=True, default='Нет', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='wifi',
            field=models.CharField(blank=True, default='Нет', max_length=10),
        ),
    ]
