# Generated by Django 2.2.6 on 2021-07-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_category', to='categories.Category', verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='parking',
            field=models.CharField(blank=True, default='Нет', max_length=20, verbose_name='Парковка:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='wifi',
            field=models.CharField(blank=True, default='Нет', max_length=10, verbose_name='Wifi:'),
        ),
    ]
