# Generated by Django 2.2.6 on 2021-07-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210722_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='hotel',
            new_name='hotels',
        ),
    ]
