# Generated by Django 2.2.6 on 2021-07-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210722_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='hotels',
            new_name='movie',
        ),
    ]
