# Generated by Django 2.2.6 on 2021-07-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20210722_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='hostel',
            new_name='hotel',
        ),
    ]
